### ISSUE TITLE
Troubles compiling iXSensINS

### ISSUE THREAD

**Issue by SimonRohou** [ENSTABretagneRobotics/moos-ivp-toutatis#34]
This kind of error:

include/xsens/xsquaternion.h:39:11: error: ‘XsReal XsQuaternion::<anonymous union>::<anonymous struct>::m_w’ is protected
    XsReal m_w;  //!< Stores the w component of the quaternion

**Comment by ThomasLeMezo** [comment]
In the API_XSens folder, could you try:

```
make clean
make
```

and copy-past the errors?

**Comment by SimonRohou** [comment]
The result:

```
make -C xstypes  libxstypes.a
make[1]: Entering directory '/home/simon/moos-ivp-toutatis/src/app/iXSensINS/API_XSens/xstypes'
cc -c -I../include/xsens xsthread.c -o xsthread.c.o
cc -c -I../include/xsens xsdatapacket.c -o xsdatapacket.c.o
cc -c -I../include/xsens xsstringarray.c -o xsstringarray.c.o
cc -c -I../include/xsens xsresultvalue.c -o xsresultvalue.c.o
cc -c -I../include/xsens xsportinfoarray.c -o xsportinfoarray.c.o
cc -c -I../include/xsens xsint64array.c -o xsint64array.c.o
cc -c -I../include/xsens xsquaternion.c -o xsquaternion.c.o
cc -c -I../include/xsens xsbytearray.c -o xsbytearray.c.o
cc -c -I../include/xsens xsmalloc.c -o xsmalloc.c.o
cc -c -I../include/xsens xstime.c -o xstime.c.o
cc -c -I../include/xsens xsportinfo.c -o xsportinfo.c.o
cc -c -I../include/xsens xscalibrateddata.c -o xscalibrateddata.c.o
cc -c -I../include/xsens xssdidata.c -o xssdidata.c.o
cc -c -I../include/xsens xsoutputconfigurationarray.c -o xsoutputconfigurationarray.c.o
cc -c -I../include/xsens xsgpspvtdata.c -o xsgpspvtdata.c.o
cc -c -I../include/xsens xsfile.c -o xsfile.c.o
cc -c -I../include/xsens xsoutputconfiguration.c -o xsoutputconfiguration.c.o
cc -c -I../include/xsens xslibraryloader.c -o xslibraryloader.c.o
cc -c -I../include/xsens xsmatrix.c -o xsmatrix.c.o
cc -c -I../include/xsens xsmessagearray.c -o xsmessagearray.c.o
cc -c -I../include/xsens xsrange.c -o xsrange.c.o
cc -c -I../include/xsens xssocket.c -o xssocket.c.o
cc -c -I../include/xsens xssimpleversion.c -o xssimpleversion.c.o
cc -c -I../include/xsens xsdeviceid.c -o xsdeviceid.c.o
cc -c -I../include/xsens xsmatrix3x3.c -o xsmatrix3x3.c.o
cc -c -I../include/xsens xsmessage.c -o xsmessage.c.o
cc -c -I../include/xsens xsvector3.c -o xsvector3.c.o
cc -c -I../include/xsens xstypedefs.c -o xstypedefs.c.o
cc -c -I../include/xsens xsutctime.c -o xsutctime.c.o
cc -c -I../include/xsens xsstring.c -o xsstring.c.o
cc -c -I../include/xsens xsarray.c -o xsarray.c.o
cc -c -I../include/xsens xsvector.c -o xsvector.c.o
cc -c -I../include/xsens xstriggerindicationdata.c -o xstriggerindicationdata.c.o
cc -c -I../include/xsens xssyncsetting.c -o xssyncsetting.c.o
cc -c -I../include/xsens xssyncsettingarray.c -o xssyncsettingarray.c.o
cc -c -I../include/xsens xsmath.c -o xsmath.c.o
cc -c -I../include/xsens xseuler.c -o xseuler.c.o
cc -c -I../include/xsens xsversion.c -o xsversion.c.o
cc -c -I../include/xsens xsbaud.c -o xsbaud.c.o
cc -c -I../include/xsens xstimestamp.c -o xstimestamp.c.o
cc -c -I../include/xsens xsintarray.c -o xsintarray.c.o
cc -c -I../include/xsens xsdeviceidarray.c -o xsdeviceidarray.c.o
cc -c -I../include/xsens xsrssi.c -o xsrssi.c.o
ar rcs libxstypes.a xsthread.c.o xsdatapacket.c.o xsstringarray.c.o xsresultvalue.c.o xsportinfoarray.c.o xsint64array.c.o xsquaternion.c.o xsbytearray.c.o xsmalloc.c.o xstime.c.o xsportinfo.c.o xscalibrateddata.c.o xssdidata.c.o xsoutputconfigurationarray.c.o xsgpspvtdata.c.o xsfile.c.o xsoutputconfiguration.c.o xslibraryloader.c.o xsmatrix.c.o xsmessagearray.c.o xsrange.c.o xssocket.c.o xssimpleversion.c.o xsdeviceid.c.o xsmatrix3x3.c.o xsmessage.c.o xsvector3.c.o xstypedefs.c.o xsutctime.c.o xsstring.c.o xsarray.c.o xsvector.c.o xstriggerindicationdata.c.o xssyncsetting.c.o xssyncsettingarray.c.o xsmath.c.o xseuler.c.o xsversion.c.o xsbaud.c.o xstimestamp.c.o xsintarray.c.o xsdeviceidarray.c.o xsrssi.c.o
make[1]: Leaving directory '/home/simon/moos-ivp-toutatis/src/app/iXSensINS/API_XSens/xstypes'
make -C xcommunication 
make[1]: Entering directory '/home/simon/moos-ivp-toutatis/src/app/iXSensINS/API_XSens/xcommunication'
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h iointerfacefile.cpp -o iointerfacefile.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h xsudev.cpp -o xsudev.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h enumerateusbdevices.cpp -o enumerateusbdevices.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h iointerface.cpp -o iointerface.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h legacydatapacket.cpp -o legacydatapacket.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h usbinterface.cpp -o usbinterface.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h xslibusb.cpp -o xslibusb.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h mtwsdidata.cpp -o mtwsdidata.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h int_xsdatapacket.cpp -o int_xsdatapacket.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h xswinusb.cpp -o xswinusb.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h serialinterface.cpp -o serialinterface.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h packetfixeddata.cpp -o packetfixeddata.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h protocolhandler.cpp -o protocolhandler.cpp.o
g++ -c -I../include -I../include/xcommunication -include xcommunicationconfig.h packetstamper.cpp -o packetstamper.cpp.o
cc -c -I../include -I../include/xcommunication -include xcommunicationconfig.h synclinemk4.c -o synclinemk4.c.o
ar rcs libxcommunication.a iointerfacefile.cpp.o xsudev.cpp.o enumerateusbdevices.cpp.o iointerface.cpp.o legacydatapacket.cpp.o usbinterface.cpp.o xslibusb.cpp.o mtwsdidata.cpp.o int_xsdatapacket.cpp.o xswinusb.cpp.o serialinterface.cpp.o packetfixeddata.cpp.o protocolhandler.cpp.o packetstamper.cpp.o synclinemk4.c.o
make[1]: Leaving directory '/home/simon/moos-ivp-toutatis/src/app/iXSensINS/API_XSens/xcommunication'
g++ -g -I. -Iinclude -include config.h   -c -o deviceclass.o deviceclass.cpp
g++ -g -I. -Iinclude -include config.h   -c -o example_mt_ix_mk4.o example_mt_ix_mk4.cpp
In file included from include/xsens/xssdidata.h:6:0,
                 from include/xsens/xsdatapacket.h:14,
                 from example_mt_ix_mk4.cpp:15:
include/xsens/xsquaternion.h: In function ‘int main(int, char**)’:
include/xsens/xsquaternion.h:39:11: error: ‘XsReal XsQuaternion::<anonymous union>::<anonymous struct>::m_w’ is protected
    XsReal m_w;  //!< Stores the w component of the quaternion
           ^
example_mt_ix_mk4.cpp:159:86: error: within this context
          << "W:" << std::setw(5) << std::fixed << std::setprecision(2) << quaternion.m_w
                                                                                      ^
In file included from include/xsens/xssdidata.h:6:0,
                 from include/xsens/xsdatapacket.h:14,
                 from example_mt_ix_mk4.cpp:15:
include/xsens/xsquaternion.h:40:11: error: ‘XsReal XsQuaternion::<anonymous union>::<anonymous struct>::m_x’ is protected
    XsReal m_x;  //!< Stores the x component of the quaternion
           ^
example_mt_ix_mk4.cpp:160:87: error: within this context
          << ",X:" << std::setw(5) << std::fixed << std::setprecision(2) << quaternion.m_x
                                                                                       ^
In file included from include/xsens/xssdidata.h:6:0,
                 from include/xsens/xsdatapacket.h:14,
                 from example_mt_ix_mk4.cpp:15:
include/xsens/xsquaternion.h:41:11: error: ‘XsReal XsQuaternion::<anonymous union>::<anonymous struct>::m_y’ is protected
    XsReal m_y;  //!< Stores the y component of the quaternion
           ^
example_mt_ix_mk4.cpp:161:87: error: within this context
          << ",Y:" << std::setw(5) << std::fixed << std::setprecision(2) << quaternion.m_y
                                                                                       ^
In file included from include/xsens/xssdidata.h:6:0,
                 from include/xsens/xsdatapacket.h:14,
                 from example_mt_ix_mk4.cpp:15:
include/xsens/xsquaternion.h:42:11: error: ‘XsReal XsQuaternion::<anonymous union>::<anonymous struct>::m_z’ is protected
    XsReal m_z;  //!< Stores the z component of the quaternion
           ^
example_mt_ix_mk4.cpp:162:87: error: within this context
          << ",Z:" << std::setw(5) << std::fixed << std::setprecision(2) << quaternion.m_z
                                                                                       ^
In file included from include/xsens/xsdatapacket.h:18:0,
                 from example_mt_ix_mk4.cpp:15:
include/xsens/xseuler.h:119:11: error: ‘XsReal XsEuler::<anonymous union>::<anonymous struct>::m_roll’ is private
    XsReal m_roll;  //!< Stores the roll component of the euler triplet
           ^
example_mt_ix_mk4.cpp:167:91: error: within this context
      std::cout << ",Roll:" << std::setw(7) << std::fixed << std::setprecision(2) << euler.m_roll
                                                                                           ^
In file included from include/xsens/xsdatapacket.h:18:0,
                 from example_mt_ix_mk4.cpp:15:
include/xsens/xseuler.h:120:11: error: ‘XsReal XsEuler::<anonymous union>::<anonymous struct>::m_pitch’ is private
    XsReal m_pitch;  //!< Stores the pitch component of the euler triplet
           ^
example_mt_ix_mk4.cpp:168:86: error: within this context
          << ",Pitch:" << std::setw(7) << std::fixed << std::setprecision(2) << euler.m_pitch
                                                                                      ^
In file included from include/xsens/xsdatapacket.h:18:0,
                 from example_mt_ix_mk4.cpp:15:
include/xsens/xseuler.h:121:11: error: ‘XsReal XsEuler::<anonymous union>::<anonymous struct>::m_yaw’ is private
    XsReal m_yaw;  //!< Stores the yaw component of the euler triplet
           ^
example_mt_ix_mk4.cpp:169:84: error: within this context
          << ",Yaw:" << std::setw(7) << std::fixed << std::setprecision(2) << euler.m_yaw
                                                                                    ^
<builtin>: recipe for target 'example_mt_ix_mk4.o' failed
make: *** [example_mt_ix_mk4.o] Error 1
```

**Comment by SimonRohou** [comment]
With: `gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13)`

**Comment by nicolaje** [comment]
Did you git pull the latest changes?
e72efd7d40fa47b3f83d75d45289c6830741d382 should solve this

**Comment by ThomasLeMezo** [comment]
Works with gcc version 4.8.4

**Comment by SimonRohou** [comment]
Sorry guys, thx Jeremy.
