### PR TITLE
Casted ints to floats in parse.c. It now builds with gcc 5.4.0 on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by jogama**
I was getting this error when building:  
```$ src/parse.c:908:3: error: non-floating-point argument in call to function ‘__builtin_isnan’```

So I casted to float. I'm not familiar with C, so any criticisms are welcome.

### CODE REVIEW

**Comment by jogama** [comment]
Before this commit: `$ iPololu -i`
```
    $(MOOSVAR_SUBSCRIPTION) (double):   
    set PWM value based on a ratio belonging to the set [-1;1]
```
After: `$ iPololu -i`
```
    $(MOOSVAR_SUBSCRIPTION) (double):   
    set PWM value based on a ratio belonging to the set [-100;100]
```

I struggled with this app for some time until I looked at [PololuPinOut.cpp](https://github.com/ENSTABretagneRobotics/moos-ivp-enstabretagne/blob/master/src/app/interfaces/iPololu/PololuPinOut.cpp). The code uses the range [-100,100]. This commit reflects this.

**Comment by jogama** [comment]
(pardon, I accidentally closed the pull request)

One other note is that this request includes the changes in pr #166

**Comment by SimonRohou** [comment]
Thanks!
